import std::error::StandardError
import std::test::*

def tests(t: Tests) {
  t.group('std::error::StandardError.to_string') do (g) {
    g.test('Converting a StandardError to a String') {
      let error = StandardError.new('hello')

      try assert_equal(error.to_string, 'hello')
    }
  }

  t.group('std::error::StandardError.message') do (g) {
    g.test('Obtaining the message from a StandardError') {
      let error = StandardError.new('hello')

      try assert_equal(error.message, 'hello')
    }
  }
}
